on:
  push:
    tags:
      - "*"

name: Build & Release

jobs:
  build:
    name: Build & Release APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Build APK
        run: |
          flutter packages pub get
          flutter packages pub run build_runner build --delete-conflicting-outputs
          flutter build apk --split-per-abi
        env:
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*"
          token: ${{secrets.RELEASE}}