name: Analyze & Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: "stable"

      - name: Fetch packages
        run: flutter packages pub get
          
      - name: Code Generation
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Run analyzer
        run: flutter analyze --no-fatal-infos
          
      - name: Run tests
        run: flutter test
