name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Flutter
        uses: subosito/flutter-action@v2
        with:
            channel: "stable"

      - name: Get Packages
        run: flutter packages pub get
          
      - name: Code Generation
        run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - name: Run Analyzer
        run: flutter analyze --no-fatal-infos
          
      - name: Run Test
        run: flutter test --coverage
      
      - name: Code Coverage
        run: |
          sudo apt-get install -y lcov
          lcov --remove coverage/lcov.info 'lib/*/*.freezed.dart' 'lib/*/*.g.dart' -o coverage/lcov.info
      
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          file: coverage/lcov.info
          token: "${{secrets.CODECOV}}"
